// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: proto/k8s.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common request/response messages
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_k8s_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{0}
}

func (x *ListRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_k8s_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Pod messages
type PodListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pods          []*Pod                 `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodListResponse) Reset() {
	*x = PodListResponse{}
	mi := &file_proto_k8s_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodListResponse) ProtoMessage() {}

func (x *PodListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodListResponse.ProtoReflect.Descriptor instead.
func (*PodListResponse) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{2}
}

func (x *PodListResponse) GetPods() []*Pod {
	if x != nil {
		return x.Pods
	}
	return nil
}

type Pod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Node          string                 `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	Age           string                 `protobuf:"bytes,5,opt,name=age,proto3" json:"age,omitempty"`
	Containers    []*Container           `protobuf:"bytes,6,rep,name=containers,proto3" json:"containers,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pod) Reset() {
	*x = Pod{}
	mi := &file_proto_k8s_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{3}
}

func (x *Pod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pod) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Pod) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Pod) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *Pod) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *Pod) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *Pod) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Ports         []*Port                `protobuf:"bytes,4,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_proto_k8s_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{4}
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Container) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

type Port struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ContainerPort int32                  `protobuf:"varint,2,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_proto_k8s_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{5}
}

func (x *Port) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Port) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

type CreatePodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Spec          *PodSpec               `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePodRequest) Reset() {
	*x = CreatePodRequest{}
	mi := &file_proto_k8s_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePodRequest) ProtoMessage() {}

func (x *CreatePodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePodRequest.ProtoReflect.Descriptor instead.
func (*CreatePodRequest) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePodRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreatePodRequest) GetSpec() *PodSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type PodSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Containers    []*ContainerSpec       `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodSpec) Reset() {
	*x = PodSpec{}
	mi := &file_proto_k8s_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodSpec) ProtoMessage() {}

func (x *PodSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodSpec.ProtoReflect.Descriptor instead.
func (*PodSpec) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{7}
}

func (x *PodSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodSpec) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *PodSpec) GetContainers() []*ContainerSpec {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ContainerSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Ports         []*PortSpec            `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerSpec) Reset() {
	*x = ContainerSpec{}
	mi := &file_proto_k8s_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerSpec) ProtoMessage() {}

func (x *ContainerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerSpec.ProtoReflect.Descriptor instead.
func (*ContainerSpec) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{8}
}

func (x *ContainerSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerSpec) GetPorts() []*PortSpec {
	if x != nil {
		return x.Ports
	}
	return nil
}

type PortSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ContainerPort int32                  `protobuf:"varint,2,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortSpec) Reset() {
	*x = PortSpec{}
	mi := &file_proto_k8s_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortSpec) ProtoMessage() {}

func (x *PortSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortSpec.ProtoReflect.Descriptor instead.
func (*PortSpec) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{9}
}

func (x *PortSpec) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *PortSpec) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

type UpdatePodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Spec          *PodSpec               `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePodRequest) Reset() {
	*x = UpdatePodRequest{}
	mi := &file_proto_k8s_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePodRequest) ProtoMessage() {}

func (x *UpdatePodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePodRequest.ProtoReflect.Descriptor instead.
func (*UpdatePodRequest) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePodRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpdatePodRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePodRequest) GetSpec() *PodSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type PodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pod           *Pod                   `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodResponse) Reset() {
	*x = PodResponse{}
	mi := &file_proto_k8s_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodResponse) ProtoMessage() {}

func (x *PodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodResponse.ProtoReflect.Descriptor instead.
func (*PodResponse) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{11}
}

func (x *PodResponse) GetPod() *Pod {
	if x != nil {
		return x.Pod
	}
	return nil
}

// Deployment messages
type DeploymentListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployments   []*Deployment          `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentListResponse) Reset() {
	*x = DeploymentListResponse{}
	mi := &file_proto_k8s_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentListResponse) ProtoMessage() {}

func (x *DeploymentListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentListResponse.ProtoReflect.Descriptor instead.
func (*DeploymentListResponse) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{12}
}

func (x *DeploymentListResponse) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

type Deployment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace         string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Replicas          int32                  `protobuf:"varint,3,opt,name=replicas,proto3" json:"replicas,omitempty"`
	ReadyReplicas     int32                  `protobuf:"varint,4,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	AvailableReplicas int32                  `protobuf:"varint,5,opt,name=available_replicas,json=availableReplicas,proto3" json:"available_replicas,omitempty"`
	Age               string                 `protobuf:"bytes,6,opt,name=age,proto3" json:"age,omitempty"`
	Labels            map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_proto_k8s_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{13}
}

func (x *Deployment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Deployment) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Deployment) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *Deployment) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *Deployment) GetAvailableReplicas() int32 {
	if x != nil {
		return x.AvailableReplicas
	}
	return 0
}

func (x *Deployment) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *Deployment) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type CreateDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Spec          *DeploymentSpec        `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeploymentRequest) Reset() {
	*x = CreateDeploymentRequest{}
	mi := &file_proto_k8s_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeploymentRequest) ProtoMessage() {}

func (x *CreateDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeploymentRequest.ProtoReflect.Descriptor instead.
func (*CreateDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{14}
}

func (x *CreateDeploymentRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateDeploymentRequest) GetSpec() *DeploymentSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type DeploymentSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Replicas      int32                  `protobuf:"varint,2,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Template      *PodSpec               `protobuf:"bytes,4,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentSpec) Reset() {
	*x = DeploymentSpec{}
	mi := &file_proto_k8s_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentSpec) ProtoMessage() {}

func (x *DeploymentSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentSpec.ProtoReflect.Descriptor instead.
func (*DeploymentSpec) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{15}
}

func (x *DeploymentSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeploymentSpec) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *DeploymentSpec) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DeploymentSpec) GetTemplate() *PodSpec {
	if x != nil {
		return x.Template
	}
	return nil
}

type UpdateDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Spec          *DeploymentSpec        `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeploymentRequest) Reset() {
	*x = UpdateDeploymentRequest{}
	mi := &file_proto_k8s_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeploymentRequest) ProtoMessage() {}

func (x *UpdateDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeploymentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateDeploymentRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpdateDeploymentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDeploymentRequest) GetSpec() *DeploymentSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type DeploymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    *Deployment            `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentResponse) Reset() {
	*x = DeploymentResponse{}
	mi := &file_proto_k8s_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentResponse) ProtoMessage() {}

func (x *DeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentResponse.ProtoReflect.Descriptor instead.
func (*DeploymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{17}
}

func (x *DeploymentResponse) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

// Service messages
type ServiceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceListResponse) Reset() {
	*x = ServiceListResponse{}
	mi := &file_proto_k8s_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceListResponse) ProtoMessage() {}

func (x *ServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceListResponse.ProtoReflect.Descriptor instead.
func (*ServiceListResponse) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{18}
}

func (x *ServiceListResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	ClusterIp     string                 `protobuf:"bytes,4,opt,name=cluster_ip,json=clusterIp,proto3" json:"cluster_ip,omitempty"`
	ExternalIp    string                 `protobuf:"bytes,5,opt,name=external_ip,json=externalIp,proto3" json:"external_ip,omitempty"`
	Ports         []string               `protobuf:"bytes,6,rep,name=ports,proto3" json:"ports,omitempty"`
	Age           string                 `protobuf:"bytes,7,opt,name=age,proto3" json:"age,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_proto_k8s_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{19}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Service) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Service) GetClusterIp() string {
	if x != nil {
		return x.ClusterIp
	}
	return ""
}

func (x *Service) GetExternalIp() string {
	if x != nil {
		return x.ExternalIp
	}
	return ""
}

func (x *Service) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *Service) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *Service) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type CreateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Spec          *ServiceSpec           `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceRequest) Reset() {
	*x = CreateServiceRequest{}
	mi := &file_proto_k8s_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceRequest) ProtoMessage() {}

func (x *CreateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{20}
}

func (x *CreateServiceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateServiceRequest) GetSpec() *ServiceSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ServiceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Ports         []*PortSpec            `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	Selector      map[string]string      `protobuf:"bytes,4,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceSpec) Reset() {
	*x = ServiceSpec{}
	mi := &file_proto_k8s_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceSpec) ProtoMessage() {}

func (x *ServiceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceSpec.ProtoReflect.Descriptor instead.
func (*ServiceSpec) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{21}
}

func (x *ServiceSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServiceSpec) GetPorts() []*PortSpec {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ServiceSpec) GetSelector() map[string]string {
	if x != nil {
		return x.Selector
	}
	return nil
}

type UpdateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Spec          *ServiceSpec           `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceRequest) Reset() {
	*x = UpdateServiceRequest{}
	mi := &file_proto_k8s_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceRequest) ProtoMessage() {}

func (x *UpdateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateServiceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpdateServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateServiceRequest) GetSpec() *ServiceSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *Service               `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceResponse) Reset() {
	*x = ServiceResponse{}
	mi := &file_proto_k8s_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResponse) ProtoMessage() {}

func (x *ServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResponse.ProtoReflect.Descriptor instead.
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{23}
}

func (x *ServiceResponse) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

// ConfigMap messages
type ConfigMapListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configmaps    []*ConfigMap           `protobuf:"bytes,1,rep,name=configmaps,proto3" json:"configmaps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMapListResponse) Reset() {
	*x = ConfigMapListResponse{}
	mi := &file_proto_k8s_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMapListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMapListResponse) ProtoMessage() {}

func (x *ConfigMapListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMapListResponse.ProtoReflect.Descriptor instead.
func (*ConfigMapListResponse) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{24}
}

func (x *ConfigMapListResponse) GetConfigmaps() []*ConfigMap {
	if x != nil {
		return x.Configmaps
	}
	return nil
}

type ConfigMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Age           string                 `protobuf:"bytes,4,opt,name=age,proto3" json:"age,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMap) Reset() {
	*x = ConfigMap{}
	mi := &file_proto_k8s_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMap) ProtoMessage() {}

func (x *ConfigMap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMap.ProtoReflect.Descriptor instead.
func (*ConfigMap) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{25}
}

func (x *ConfigMap) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigMap) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ConfigMap) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ConfigMap) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *ConfigMap) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type CreateConfigMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Spec          *ConfigMapSpec         `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConfigMapRequest) Reset() {
	*x = CreateConfigMapRequest{}
	mi := &file_proto_k8s_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConfigMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConfigMapRequest) ProtoMessage() {}

func (x *CreateConfigMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConfigMapRequest.ProtoReflect.Descriptor instead.
func (*CreateConfigMapRequest) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{26}
}

func (x *CreateConfigMapRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateConfigMapRequest) GetSpec() *ConfigMapSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ConfigMapSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          map[string]string      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMapSpec) Reset() {
	*x = ConfigMapSpec{}
	mi := &file_proto_k8s_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMapSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMapSpec) ProtoMessage() {}

func (x *ConfigMapSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMapSpec.ProtoReflect.Descriptor instead.
func (*ConfigMapSpec) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{27}
}

func (x *ConfigMapSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigMapSpec) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ConfigMapSpec) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type UpdateConfigMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Spec          *ConfigMapSpec         `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigMapRequest) Reset() {
	*x = UpdateConfigMapRequest{}
	mi := &file_proto_k8s_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigMapRequest) ProtoMessage() {}

func (x *UpdateConfigMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigMapRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigMapRequest) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateConfigMapRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpdateConfigMapRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateConfigMapRequest) GetSpec() *ConfigMapSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ConfigMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configmap     *ConfigMap             `protobuf:"bytes,1,opt,name=configmap,proto3" json:"configmap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMapResponse) Reset() {
	*x = ConfigMapResponse{}
	mi := &file_proto_k8s_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMapResponse) ProtoMessage() {}

func (x *ConfigMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMapResponse.ProtoReflect.Descriptor instead.
func (*ConfigMapResponse) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{29}
}

func (x *ConfigMapResponse) GetConfigmap() *ConfigMap {
	if x != nil {
		return x.Configmap
	}
	return nil
}

// Namespace messages
type NamespaceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []*Namespace           `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceListResponse) Reset() {
	*x = NamespaceListResponse{}
	mi := &file_proto_k8s_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceListResponse) ProtoMessage() {}

func (x *NamespaceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceListResponse.ProtoReflect.Descriptor instead.
func (*NamespaceListResponse) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{30}
}

func (x *NamespaceListResponse) GetNamespaces() []*Namespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type Namespace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Age           string                 `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_proto_k8s_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{31}
}

func (x *Namespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Namespace) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Namespace) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

// Pod logs and exec messages
type PodLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName       string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	ContainerName string                 `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	TailLines     int32                  `protobuf:"varint,4,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	Follow        bool                   `protobuf:"varint,5,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodLogsRequest) Reset() {
	*x = PodLogsRequest{}
	mi := &file_proto_k8s_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodLogsRequest) ProtoMessage() {}

func (x *PodLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodLogsRequest.ProtoReflect.Descriptor instead.
func (*PodLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{32}
}

func (x *PodLogsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodLogsRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PodLogsRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *PodLogsRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *PodLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type LogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          string                 `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_proto_k8s_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{33}
}

func (x *LogsResponse) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName       string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	ContainerName string                 `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_proto_k8s_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{34}
}

func (x *ExecRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ExecRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *ExecRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	IsError       bool                   `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_proto_k8s_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_k8s_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_proto_k8s_proto_rawDescGZIP(), []int{35}
}

func (x *ExecResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

var File_proto_k8s_proto protoreflect.FileDescriptor

const file_proto_k8s_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/k8s.proto\x12\x03k8s\x1a\x1bgoogle/protobuf/empty.proto\"+\n" +
	"\vListRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"A\n" +
	"\rDeleteRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"/\n" +
	"\x0fPodListResponse\x12\x1c\n" +
	"\x04pods\x18\x01 \x03(\v2\b.k8s.PodR\x04pods\"\x8e\x02\n" +
	"\x03Pod\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04node\x18\x04 \x01(\tR\x04node\x12\x10\n" +
	"\x03age\x18\x05 \x01(\tR\x03age\x12.\n" +
	"\n" +
	"containers\x18\x06 \x03(\v2\x0e.k8s.ContainerR\n" +
	"containers\x12,\n" +
	"\x06labels\x18\a \x03(\v2\x14.k8s.Pod.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\tContainer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\x05ports\x18\x04 \x03(\v2\t.k8s.PortR\x05ports\"I\n" +
	"\x04Port\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12%\n" +
	"\x0econtainer_port\x18\x02 \x01(\x05R\rcontainerPort\"R\n" +
	"\x10CreatePodRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12 \n" +
	"\x04spec\x18\x02 \x01(\v2\f.k8s.PodSpecR\x04spec\"\xbe\x01\n" +
	"\aPodSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x06labels\x18\x02 \x03(\v2\x18.k8s.PodSpec.LabelsEntryR\x06labels\x122\n" +
	"\n" +
	"containers\x18\x03 \x03(\v2\x12.k8s.ContainerSpecR\n" +
	"containers\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\rContainerSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12#\n" +
	"\x05ports\x18\x03 \x03(\v2\r.k8s.PortSpecR\x05ports\"M\n" +
	"\bPortSpec\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12%\n" +
	"\x0econtainer_port\x18\x02 \x01(\x05R\rcontainerPort\"f\n" +
	"\x10UpdatePodRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\x04spec\x18\x03 \x01(\v2\f.k8s.PodSpecR\x04spec\")\n" +
	"\vPodResponse\x12\x1a\n" +
	"\x03pod\x18\x01 \x01(\v2\b.k8s.PodR\x03pod\"K\n" +
	"\x16DeploymentListResponse\x121\n" +
	"\vdeployments\x18\x01 \x03(\v2\x0f.k8s.DeploymentR\vdeployments\"\xb2\x02\n" +
	"\n" +
	"Deployment\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1a\n" +
	"\breplicas\x18\x03 \x01(\x05R\breplicas\x12%\n" +
	"\x0eready_replicas\x18\x04 \x01(\x05R\rreadyReplicas\x12-\n" +
	"\x12available_replicas\x18\x05 \x01(\x05R\x11availableReplicas\x12\x10\n" +
	"\x03age\x18\x06 \x01(\tR\x03age\x123\n" +
	"\x06labels\x18\a \x03(\v2\x1b.k8s.Deployment.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\x17CreateDeploymentRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12'\n" +
	"\x04spec\x18\x02 \x01(\v2\x13.k8s.DeploymentSpecR\x04spec\"\xde\x01\n" +
	"\x0eDeploymentSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\breplicas\x18\x02 \x01(\x05R\breplicas\x127\n" +
	"\x06labels\x18\x03 \x03(\v2\x1f.k8s.DeploymentSpec.LabelsEntryR\x06labels\x12(\n" +
	"\btemplate\x18\x04 \x01(\v2\f.k8s.PodSpecR\btemplate\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\x17UpdateDeploymentRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x04spec\x18\x03 \x01(\v2\x13.k8s.DeploymentSpecR\x04spec\"E\n" +
	"\x12DeploymentResponse\x12/\n" +
	"\n" +
	"deployment\x18\x01 \x01(\v2\x0f.k8s.DeploymentR\n" +
	"deployment\"?\n" +
	"\x13ServiceListResponse\x12(\n" +
	"\bservices\x18\x01 \x03(\v2\f.k8s.ServiceR\bservices\"\xa4\x02\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"cluster_ip\x18\x04 \x01(\tR\tclusterIp\x12\x1f\n" +
	"\vexternal_ip\x18\x05 \x01(\tR\n" +
	"externalIp\x12\x14\n" +
	"\x05ports\x18\x06 \x03(\tR\x05ports\x12\x10\n" +
	"\x03age\x18\a \x01(\tR\x03age\x120\n" +
	"\x06labels\x18\b \x03(\v2\x18.k8s.Service.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\x14CreateServiceRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12$\n" +
	"\x04spec\x18\x02 \x01(\v2\x10.k8s.ServiceSpecR\x04spec\"\xd3\x01\n" +
	"\vServiceSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12#\n" +
	"\x05ports\x18\x03 \x03(\v2\r.k8s.PortSpecR\x05ports\x12:\n" +
	"\bselector\x18\x04 \x03(\v2\x1e.k8s.ServiceSpec.SelectorEntryR\bselector\x1a;\n" +
	"\rSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\x14UpdateServiceRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x04spec\x18\x03 \x01(\v2\x10.k8s.ServiceSpecR\x04spec\"9\n" +
	"\x0fServiceResponse\x12&\n" +
	"\aservice\x18\x01 \x01(\v2\f.k8s.ServiceR\aservice\"G\n" +
	"\x15ConfigMapListResponse\x12.\n" +
	"\n" +
	"configmaps\x18\x01 \x03(\v2\x0e.k8s.ConfigMapR\n" +
	"configmaps\"\xa5\x02\n" +
	"\tConfigMap\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12,\n" +
	"\x04data\x18\x03 \x03(\v2\x18.k8s.ConfigMap.DataEntryR\x04data\x12\x10\n" +
	"\x03age\x18\x04 \x01(\tR\x03age\x122\n" +
	"\x06labels\x18\x05 \x03(\v2\x1a.k8s.ConfigMap.LabelsEntryR\x06labels\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\x16CreateConfigMapRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12&\n" +
	"\x04spec\x18\x02 \x01(\v2\x12.k8s.ConfigMapSpecR\x04spec\"\x81\x02\n" +
	"\rConfigMapSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x04data\x18\x02 \x03(\v2\x1c.k8s.ConfigMapSpec.DataEntryR\x04data\x126\n" +
	"\x06labels\x18\x03 \x03(\v2\x1e.k8s.ConfigMapSpec.LabelsEntryR\x06labels\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\x16UpdateConfigMapRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x04spec\x18\x03 \x01(\v2\x12.k8s.ConfigMapSpecR\x04spec\"A\n" +
	"\x11ConfigMapResponse\x12,\n" +
	"\tconfigmap\x18\x01 \x01(\v2\x0e.k8s.ConfigMapR\tconfigmap\"G\n" +
	"\x15NamespaceListResponse\x12.\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\v2\x0e.k8s.NamespaceR\n" +
	"namespaces\"I\n" +
	"\tNamespace\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x10\n" +
	"\x03age\x18\x03 \x01(\tR\x03age\"\xa7\x01\n" +
	"\x0ePodLogsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x04 \x01(\x05R\ttailLines\x12\x16\n" +
	"\x06follow\x18\x05 \x01(\bR\x06follow\"\"\n" +
	"\fLogsResponse\x12\x12\n" +
	"\x04logs\x18\x01 \x01(\tR\x04logs\"\x87\x01\n" +
	"\vExecRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\"A\n" +
	"\fExecResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError2\xb7\t\n" +
	"\n" +
	"K8sService\x122\n" +
	"\bListPods\x12\x10.k8s.ListRequest\x1a\x14.k8s.PodListResponse\x12@\n" +
	"\x0fListDeployments\x12\x10.k8s.ListRequest\x1a\x1b.k8s.DeploymentListResponse\x12:\n" +
	"\fListServices\x12\x10.k8s.ListRequest\x1a\x18.k8s.ServiceListResponse\x12>\n" +
	"\x0eListConfigMaps\x12\x10.k8s.ListRequest\x1a\x1a.k8s.ConfigMapListResponse\x124\n" +
	"\tCreatePod\x12\x15.k8s.CreatePodRequest\x1a\x10.k8s.PodResponse\x124\n" +
	"\tUpdatePod\x12\x15.k8s.UpdatePodRequest\x1a\x10.k8s.PodResponse\x127\n" +
	"\tDeletePod\x12\x12.k8s.DeleteRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x10CreateDeployment\x12\x1c.k8s.CreateDeploymentRequest\x1a\x17.k8s.DeploymentResponse\x12I\n" +
	"\x10UpdateDeployment\x12\x1c.k8s.UpdateDeploymentRequest\x1a\x17.k8s.DeploymentResponse\x12>\n" +
	"\x10DeleteDeployment\x12\x12.k8s.DeleteRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\rCreateService\x12\x19.k8s.CreateServiceRequest\x1a\x14.k8s.ServiceResponse\x12@\n" +
	"\rUpdateService\x12\x19.k8s.UpdateServiceRequest\x1a\x14.k8s.ServiceResponse\x12;\n" +
	"\rDeleteService\x12\x12.k8s.DeleteRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\x0fCreateConfigMap\x12\x1b.k8s.CreateConfigMapRequest\x1a\x16.k8s.ConfigMapResponse\x12F\n" +
	"\x0fUpdateConfigMap\x12\x1b.k8s.UpdateConfigMapRequest\x1a\x16.k8s.ConfigMapResponse\x12=\n" +
	"\x0fDeleteConfigMap\x12\x12.k8s.DeleteRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\x0eListNamespaces\x12\x16.google.protobuf.Empty\x1a\x1a.k8s.NamespaceListResponse\x124\n" +
	"\n" +
	"GetPodLogs\x12\x13.k8s.PodLogsRequest\x1a\x11.k8s.LogsResponse\x120\n" +
	"\aExecPod\x12\x10.k8s.ExecRequest\x1a\x11.k8s.ExecResponse0\x01B\x15Z\x13k8s-dashboard/protob\x06proto3"

var (
	file_proto_k8s_proto_rawDescOnce sync.Once
	file_proto_k8s_proto_rawDescData []byte
)

func file_proto_k8s_proto_rawDescGZIP() []byte {
	file_proto_k8s_proto_rawDescOnce.Do(func() {
		file_proto_k8s_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_k8s_proto_rawDesc), len(file_proto_k8s_proto_rawDesc)))
	})
	return file_proto_k8s_proto_rawDescData
}

var file_proto_k8s_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_proto_k8s_proto_goTypes = []any{
	(*ListRequest)(nil),             // 0: k8s.ListRequest
	(*DeleteRequest)(nil),           // 1: k8s.DeleteRequest
	(*PodListResponse)(nil),         // 2: k8s.PodListResponse
	(*Pod)(nil),                     // 3: k8s.Pod
	(*Container)(nil),               // 4: k8s.Container
	(*Port)(nil),                    // 5: k8s.Port
	(*CreatePodRequest)(nil),        // 6: k8s.CreatePodRequest
	(*PodSpec)(nil),                 // 7: k8s.PodSpec
	(*ContainerSpec)(nil),           // 8: k8s.ContainerSpec
	(*PortSpec)(nil),                // 9: k8s.PortSpec
	(*UpdatePodRequest)(nil),        // 10: k8s.UpdatePodRequest
	(*PodResponse)(nil),             // 11: k8s.PodResponse
	(*DeploymentListResponse)(nil),  // 12: k8s.DeploymentListResponse
	(*Deployment)(nil),              // 13: k8s.Deployment
	(*CreateDeploymentRequest)(nil), // 14: k8s.CreateDeploymentRequest
	(*DeploymentSpec)(nil),          // 15: k8s.DeploymentSpec
	(*UpdateDeploymentRequest)(nil), // 16: k8s.UpdateDeploymentRequest
	(*DeploymentResponse)(nil),      // 17: k8s.DeploymentResponse
	(*ServiceListResponse)(nil),     // 18: k8s.ServiceListResponse
	(*Service)(nil),                 // 19: k8s.Service
	(*CreateServiceRequest)(nil),    // 20: k8s.CreateServiceRequest
	(*ServiceSpec)(nil),             // 21: k8s.ServiceSpec
	(*UpdateServiceRequest)(nil),    // 22: k8s.UpdateServiceRequest
	(*ServiceResponse)(nil),         // 23: k8s.ServiceResponse
	(*ConfigMapListResponse)(nil),   // 24: k8s.ConfigMapListResponse
	(*ConfigMap)(nil),               // 25: k8s.ConfigMap
	(*CreateConfigMapRequest)(nil),  // 26: k8s.CreateConfigMapRequest
	(*ConfigMapSpec)(nil),           // 27: k8s.ConfigMapSpec
	(*UpdateConfigMapRequest)(nil),  // 28: k8s.UpdateConfigMapRequest
	(*ConfigMapResponse)(nil),       // 29: k8s.ConfigMapResponse
	(*NamespaceListResponse)(nil),   // 30: k8s.NamespaceListResponse
	(*Namespace)(nil),               // 31: k8s.Namespace
	(*PodLogsRequest)(nil),          // 32: k8s.PodLogsRequest
	(*LogsResponse)(nil),            // 33: k8s.LogsResponse
	(*ExecRequest)(nil),             // 34: k8s.ExecRequest
	(*ExecResponse)(nil),            // 35: k8s.ExecResponse
	nil,                             // 36: k8s.Pod.LabelsEntry
	nil,                             // 37: k8s.PodSpec.LabelsEntry
	nil,                             // 38: k8s.Deployment.LabelsEntry
	nil,                             // 39: k8s.DeploymentSpec.LabelsEntry
	nil,                             // 40: k8s.Service.LabelsEntry
	nil,                             // 41: k8s.ServiceSpec.SelectorEntry
	nil,                             // 42: k8s.ConfigMap.DataEntry
	nil,                             // 43: k8s.ConfigMap.LabelsEntry
	nil,                             // 44: k8s.ConfigMapSpec.DataEntry
	nil,                             // 45: k8s.ConfigMapSpec.LabelsEntry
	(*emptypb.Empty)(nil),           // 46: google.protobuf.Empty
}
var file_proto_k8s_proto_depIdxs = []int32{
	3,  // 0: k8s.PodListResponse.pods:type_name -> k8s.Pod
	4,  // 1: k8s.Pod.containers:type_name -> k8s.Container
	36, // 2: k8s.Pod.labels:type_name -> k8s.Pod.LabelsEntry
	5,  // 3: k8s.Container.ports:type_name -> k8s.Port
	7,  // 4: k8s.CreatePodRequest.spec:type_name -> k8s.PodSpec
	37, // 5: k8s.PodSpec.labels:type_name -> k8s.PodSpec.LabelsEntry
	8,  // 6: k8s.PodSpec.containers:type_name -> k8s.ContainerSpec
	9,  // 7: k8s.ContainerSpec.ports:type_name -> k8s.PortSpec
	7,  // 8: k8s.UpdatePodRequest.spec:type_name -> k8s.PodSpec
	3,  // 9: k8s.PodResponse.pod:type_name -> k8s.Pod
	13, // 10: k8s.DeploymentListResponse.deployments:type_name -> k8s.Deployment
	38, // 11: k8s.Deployment.labels:type_name -> k8s.Deployment.LabelsEntry
	15, // 12: k8s.CreateDeploymentRequest.spec:type_name -> k8s.DeploymentSpec
	39, // 13: k8s.DeploymentSpec.labels:type_name -> k8s.DeploymentSpec.LabelsEntry
	7,  // 14: k8s.DeploymentSpec.template:type_name -> k8s.PodSpec
	15, // 15: k8s.UpdateDeploymentRequest.spec:type_name -> k8s.DeploymentSpec
	13, // 16: k8s.DeploymentResponse.deployment:type_name -> k8s.Deployment
	19, // 17: k8s.ServiceListResponse.services:type_name -> k8s.Service
	40, // 18: k8s.Service.labels:type_name -> k8s.Service.LabelsEntry
	21, // 19: k8s.CreateServiceRequest.spec:type_name -> k8s.ServiceSpec
	9,  // 20: k8s.ServiceSpec.ports:type_name -> k8s.PortSpec
	41, // 21: k8s.ServiceSpec.selector:type_name -> k8s.ServiceSpec.SelectorEntry
	21, // 22: k8s.UpdateServiceRequest.spec:type_name -> k8s.ServiceSpec
	19, // 23: k8s.ServiceResponse.service:type_name -> k8s.Service
	25, // 24: k8s.ConfigMapListResponse.configmaps:type_name -> k8s.ConfigMap
	42, // 25: k8s.ConfigMap.data:type_name -> k8s.ConfigMap.DataEntry
	43, // 26: k8s.ConfigMap.labels:type_name -> k8s.ConfigMap.LabelsEntry
	27, // 27: k8s.CreateConfigMapRequest.spec:type_name -> k8s.ConfigMapSpec
	44, // 28: k8s.ConfigMapSpec.data:type_name -> k8s.ConfigMapSpec.DataEntry
	45, // 29: k8s.ConfigMapSpec.labels:type_name -> k8s.ConfigMapSpec.LabelsEntry
	27, // 30: k8s.UpdateConfigMapRequest.spec:type_name -> k8s.ConfigMapSpec
	25, // 31: k8s.ConfigMapResponse.configmap:type_name -> k8s.ConfigMap
	31, // 32: k8s.NamespaceListResponse.namespaces:type_name -> k8s.Namespace
	0,  // 33: k8s.K8sService.ListPods:input_type -> k8s.ListRequest
	0,  // 34: k8s.K8sService.ListDeployments:input_type -> k8s.ListRequest
	0,  // 35: k8s.K8sService.ListServices:input_type -> k8s.ListRequest
	0,  // 36: k8s.K8sService.ListConfigMaps:input_type -> k8s.ListRequest
	6,  // 37: k8s.K8sService.CreatePod:input_type -> k8s.CreatePodRequest
	10, // 38: k8s.K8sService.UpdatePod:input_type -> k8s.UpdatePodRequest
	1,  // 39: k8s.K8sService.DeletePod:input_type -> k8s.DeleteRequest
	14, // 40: k8s.K8sService.CreateDeployment:input_type -> k8s.CreateDeploymentRequest
	16, // 41: k8s.K8sService.UpdateDeployment:input_type -> k8s.UpdateDeploymentRequest
	1,  // 42: k8s.K8sService.DeleteDeployment:input_type -> k8s.DeleteRequest
	20, // 43: k8s.K8sService.CreateService:input_type -> k8s.CreateServiceRequest
	22, // 44: k8s.K8sService.UpdateService:input_type -> k8s.UpdateServiceRequest
	1,  // 45: k8s.K8sService.DeleteService:input_type -> k8s.DeleteRequest
	26, // 46: k8s.K8sService.CreateConfigMap:input_type -> k8s.CreateConfigMapRequest
	28, // 47: k8s.K8sService.UpdateConfigMap:input_type -> k8s.UpdateConfigMapRequest
	1,  // 48: k8s.K8sService.DeleteConfigMap:input_type -> k8s.DeleteRequest
	46, // 49: k8s.K8sService.ListNamespaces:input_type -> google.protobuf.Empty
	32, // 50: k8s.K8sService.GetPodLogs:input_type -> k8s.PodLogsRequest
	34, // 51: k8s.K8sService.ExecPod:input_type -> k8s.ExecRequest
	2,  // 52: k8s.K8sService.ListPods:output_type -> k8s.PodListResponse
	12, // 53: k8s.K8sService.ListDeployments:output_type -> k8s.DeploymentListResponse
	18, // 54: k8s.K8sService.ListServices:output_type -> k8s.ServiceListResponse
	24, // 55: k8s.K8sService.ListConfigMaps:output_type -> k8s.ConfigMapListResponse
	11, // 56: k8s.K8sService.CreatePod:output_type -> k8s.PodResponse
	11, // 57: k8s.K8sService.UpdatePod:output_type -> k8s.PodResponse
	46, // 58: k8s.K8sService.DeletePod:output_type -> google.protobuf.Empty
	17, // 59: k8s.K8sService.CreateDeployment:output_type -> k8s.DeploymentResponse
	17, // 60: k8s.K8sService.UpdateDeployment:output_type -> k8s.DeploymentResponse
	46, // 61: k8s.K8sService.DeleteDeployment:output_type -> google.protobuf.Empty
	23, // 62: k8s.K8sService.CreateService:output_type -> k8s.ServiceResponse
	23, // 63: k8s.K8sService.UpdateService:output_type -> k8s.ServiceResponse
	46, // 64: k8s.K8sService.DeleteService:output_type -> google.protobuf.Empty
	29, // 65: k8s.K8sService.CreateConfigMap:output_type -> k8s.ConfigMapResponse
	29, // 66: k8s.K8sService.UpdateConfigMap:output_type -> k8s.ConfigMapResponse
	46, // 67: k8s.K8sService.DeleteConfigMap:output_type -> google.protobuf.Empty
	30, // 68: k8s.K8sService.ListNamespaces:output_type -> k8s.NamespaceListResponse
	33, // 69: k8s.K8sService.GetPodLogs:output_type -> k8s.LogsResponse
	35, // 70: k8s.K8sService.ExecPod:output_type -> k8s.ExecResponse
	52, // [52:71] is the sub-list for method output_type
	33, // [33:52] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_proto_k8s_proto_init() }
func file_proto_k8s_proto_init() {
	if File_proto_k8s_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_k8s_proto_rawDesc), len(file_proto_k8s_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_k8s_proto_goTypes,
		DependencyIndexes: file_proto_k8s_proto_depIdxs,
		MessageInfos:      file_proto_k8s_proto_msgTypes,
	}.Build()
	File_proto_k8s_proto = out.File
	file_proto_k8s_proto_goTypes = nil
	file_proto_k8s_proto_depIdxs = nil
}
