// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: proto/k8s.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	K8SService_ListPods_FullMethodName         = "/k8s.K8sService/ListPods"
	K8SService_ListDeployments_FullMethodName  = "/k8s.K8sService/ListDeployments"
	K8SService_ListServices_FullMethodName     = "/k8s.K8sService/ListServices"
	K8SService_ListConfigMaps_FullMethodName   = "/k8s.K8sService/ListConfigMaps"
	K8SService_CreatePod_FullMethodName        = "/k8s.K8sService/CreatePod"
	K8SService_UpdatePod_FullMethodName        = "/k8s.K8sService/UpdatePod"
	K8SService_DeletePod_FullMethodName        = "/k8s.K8sService/DeletePod"
	K8SService_CreateDeployment_FullMethodName = "/k8s.K8sService/CreateDeployment"
	K8SService_UpdateDeployment_FullMethodName = "/k8s.K8sService/UpdateDeployment"
	K8SService_DeleteDeployment_FullMethodName = "/k8s.K8sService/DeleteDeployment"
	K8SService_CreateService_FullMethodName    = "/k8s.K8sService/CreateService"
	K8SService_UpdateService_FullMethodName    = "/k8s.K8sService/UpdateService"
	K8SService_DeleteService_FullMethodName    = "/k8s.K8sService/DeleteService"
	K8SService_CreateConfigMap_FullMethodName  = "/k8s.K8sService/CreateConfigMap"
	K8SService_UpdateConfigMap_FullMethodName  = "/k8s.K8sService/UpdateConfigMap"
	K8SService_DeleteConfigMap_FullMethodName  = "/k8s.K8sService/DeleteConfigMap"
	K8SService_ListNamespaces_FullMethodName   = "/k8s.K8sService/ListNamespaces"
	K8SService_GetPodLogs_FullMethodName       = "/k8s.K8sService/GetPodLogs"
	K8SService_ExecPod_FullMethodName          = "/k8s.K8sService/ExecPod"
)

// K8SServiceClient is the client API for K8SService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Kubernetes gRPC service for async operations
type K8SServiceClient interface {
	// Resource listing operations
	ListPods(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*PodListResponse, error)
	ListDeployments(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*DeploymentListResponse, error)
	ListServices(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ServiceListResponse, error)
	ListConfigMaps(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ConfigMapListResponse, error)
	// Resource CRUD operations
	CreatePod(ctx context.Context, in *CreatePodRequest, opts ...grpc.CallOption) (*PodResponse, error)
	UpdatePod(ctx context.Context, in *UpdatePodRequest, opts ...grpc.CallOption) (*PodResponse, error)
	DeletePod(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateDeployment(ctx context.Context, in *CreateDeploymentRequest, opts ...grpc.CallOption) (*DeploymentResponse, error)
	UpdateDeployment(ctx context.Context, in *UpdateDeploymentRequest, opts ...grpc.CallOption) (*DeploymentResponse, error)
	DeleteDeployment(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
	UpdateService(ctx context.Context, in *UpdateServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error)
	DeleteService(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateConfigMap(ctx context.Context, in *CreateConfigMapRequest, opts ...grpc.CallOption) (*ConfigMapResponse, error)
	UpdateConfigMap(ctx context.Context, in *UpdateConfigMapRequest, opts ...grpc.CallOption) (*ConfigMapResponse, error)
	DeleteConfigMap(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Namespace operations
	ListNamespaces(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NamespaceListResponse, error)
	// Pod logs and exec
	GetPodLogs(ctx context.Context, in *PodLogsRequest, opts ...grpc.CallOption) (*LogsResponse, error)
	ExecPod(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecResponse], error)
}

type k8SServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewK8SServiceClient(cc grpc.ClientConnInterface) K8SServiceClient {
	return &k8SServiceClient{cc}
}

func (c *k8SServiceClient) ListPods(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*PodListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PodListResponse)
	err := c.cc.Invoke(ctx, K8SService_ListPods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) ListDeployments(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*DeploymentListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeploymentListResponse)
	err := c.cc.Invoke(ctx, K8SService_ListDeployments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) ListServices(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ServiceListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceListResponse)
	err := c.cc.Invoke(ctx, K8SService_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) ListConfigMaps(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ConfigMapListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigMapListResponse)
	err := c.cc.Invoke(ctx, K8SService_ListConfigMaps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) CreatePod(ctx context.Context, in *CreatePodRequest, opts ...grpc.CallOption) (*PodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PodResponse)
	err := c.cc.Invoke(ctx, K8SService_CreatePod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) UpdatePod(ctx context.Context, in *UpdatePodRequest, opts ...grpc.CallOption) (*PodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PodResponse)
	err := c.cc.Invoke(ctx, K8SService_UpdatePod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) DeletePod(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, K8SService_DeletePod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) CreateDeployment(ctx context.Context, in *CreateDeploymentRequest, opts ...grpc.CallOption) (*DeploymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeploymentResponse)
	err := c.cc.Invoke(ctx, K8SService_CreateDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) UpdateDeployment(ctx context.Context, in *UpdateDeploymentRequest, opts ...grpc.CallOption) (*DeploymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeploymentResponse)
	err := c.cc.Invoke(ctx, K8SService_UpdateDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) DeleteDeployment(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, K8SService_DeleteDeployment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, K8SService_CreateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) UpdateService(ctx context.Context, in *UpdateServiceRequest, opts ...grpc.CallOption) (*ServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, K8SService_UpdateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) DeleteService(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, K8SService_DeleteService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) CreateConfigMap(ctx context.Context, in *CreateConfigMapRequest, opts ...grpc.CallOption) (*ConfigMapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigMapResponse)
	err := c.cc.Invoke(ctx, K8SService_CreateConfigMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) UpdateConfigMap(ctx context.Context, in *UpdateConfigMapRequest, opts ...grpc.CallOption) (*ConfigMapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigMapResponse)
	err := c.cc.Invoke(ctx, K8SService_UpdateConfigMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) DeleteConfigMap(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, K8SService_DeleteConfigMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) ListNamespaces(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NamespaceListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NamespaceListResponse)
	err := c.cc.Invoke(ctx, K8SService_ListNamespaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) GetPodLogs(ctx context.Context, in *PodLogsRequest, opts ...grpc.CallOption) (*LogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogsResponse)
	err := c.cc.Invoke(ctx, K8SService_GetPodLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SServiceClient) ExecPod(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &K8SService_ServiceDesc.Streams[0], K8SService_ExecPod_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, ExecResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type K8SService_ExecPodClient = grpc.ServerStreamingClient[ExecResponse]

// K8SServiceServer is the server API for K8SService service.
// All implementations must embed UnimplementedK8SServiceServer
// for forward compatibility.
//
// Kubernetes gRPC service for async operations
type K8SServiceServer interface {
	// Resource listing operations
	ListPods(context.Context, *ListRequest) (*PodListResponse, error)
	ListDeployments(context.Context, *ListRequest) (*DeploymentListResponse, error)
	ListServices(context.Context, *ListRequest) (*ServiceListResponse, error)
	ListConfigMaps(context.Context, *ListRequest) (*ConfigMapListResponse, error)
	// Resource CRUD operations
	CreatePod(context.Context, *CreatePodRequest) (*PodResponse, error)
	UpdatePod(context.Context, *UpdatePodRequest) (*PodResponse, error)
	DeletePod(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	CreateDeployment(context.Context, *CreateDeploymentRequest) (*DeploymentResponse, error)
	UpdateDeployment(context.Context, *UpdateDeploymentRequest) (*DeploymentResponse, error)
	DeleteDeployment(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	CreateService(context.Context, *CreateServiceRequest) (*ServiceResponse, error)
	UpdateService(context.Context, *UpdateServiceRequest) (*ServiceResponse, error)
	DeleteService(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	CreateConfigMap(context.Context, *CreateConfigMapRequest) (*ConfigMapResponse, error)
	UpdateConfigMap(context.Context, *UpdateConfigMapRequest) (*ConfigMapResponse, error)
	DeleteConfigMap(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	// Namespace operations
	ListNamespaces(context.Context, *emptypb.Empty) (*NamespaceListResponse, error)
	// Pod logs and exec
	GetPodLogs(context.Context, *PodLogsRequest) (*LogsResponse, error)
	ExecPod(*ExecRequest, grpc.ServerStreamingServer[ExecResponse]) error
	mustEmbedUnimplementedK8SServiceServer()
}

// UnimplementedK8SServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedK8SServiceServer struct{}

func (UnimplementedK8SServiceServer) ListPods(context.Context, *ListRequest) (*PodListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPods not implemented")
}
func (UnimplementedK8SServiceServer) ListDeployments(context.Context, *ListRequest) (*DeploymentListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeployments not implemented")
}
func (UnimplementedK8SServiceServer) ListServices(context.Context, *ListRequest) (*ServiceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedK8SServiceServer) ListConfigMaps(context.Context, *ListRequest) (*ConfigMapListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConfigMaps not implemented")
}
func (UnimplementedK8SServiceServer) CreatePod(context.Context, *CreatePodRequest) (*PodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePod not implemented")
}
func (UnimplementedK8SServiceServer) UpdatePod(context.Context, *UpdatePodRequest) (*PodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePod not implemented")
}
func (UnimplementedK8SServiceServer) DeletePod(context.Context, *DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePod not implemented")
}
func (UnimplementedK8SServiceServer) CreateDeployment(context.Context, *CreateDeploymentRequest) (*DeploymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeployment not implemented")
}
func (UnimplementedK8SServiceServer) UpdateDeployment(context.Context, *UpdateDeploymentRequest) (*DeploymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeployment not implemented")
}
func (UnimplementedK8SServiceServer) DeleteDeployment(context.Context, *DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDeployment not implemented")
}
func (UnimplementedK8SServiceServer) CreateService(context.Context, *CreateServiceRequest) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateService not implemented")
}
func (UnimplementedK8SServiceServer) UpdateService(context.Context, *UpdateServiceRequest) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateService not implemented")
}
func (UnimplementedK8SServiceServer) DeleteService(context.Context, *DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteService not implemented")
}
func (UnimplementedK8SServiceServer) CreateConfigMap(context.Context, *CreateConfigMapRequest) (*ConfigMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConfigMap not implemented")
}
func (UnimplementedK8SServiceServer) UpdateConfigMap(context.Context, *UpdateConfigMapRequest) (*ConfigMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfigMap not implemented")
}
func (UnimplementedK8SServiceServer) DeleteConfigMap(context.Context, *DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConfigMap not implemented")
}
func (UnimplementedK8SServiceServer) ListNamespaces(context.Context, *emptypb.Empty) (*NamespaceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNamespaces not implemented")
}
func (UnimplementedK8SServiceServer) GetPodLogs(context.Context, *PodLogsRequest) (*LogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPodLogs not implemented")
}
func (UnimplementedK8SServiceServer) ExecPod(*ExecRequest, grpc.ServerStreamingServer[ExecResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ExecPod not implemented")
}
func (UnimplementedK8SServiceServer) mustEmbedUnimplementedK8SServiceServer() {}
func (UnimplementedK8SServiceServer) testEmbeddedByValue()                    {}

// UnsafeK8SServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to K8SServiceServer will
// result in compilation errors.
type UnsafeK8SServiceServer interface {
	mustEmbedUnimplementedK8SServiceServer()
}

func RegisterK8SServiceServer(s grpc.ServiceRegistrar, srv K8SServiceServer) {
	// If the following call pancis, it indicates UnimplementedK8SServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&K8SService_ServiceDesc, srv)
}

func _K8SService_ListPods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).ListPods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K8SService_ListPods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).ListPods(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_ListDeployments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).ListDeployments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K8SService_ListDeployments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).ListDeployments(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K8SService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).ListServices(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_ListConfigMaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).ListConfigMaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K8SService_ListConfigMaps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).ListConfigMaps(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_CreatePod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).CreatePod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K8SService_CreatePod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).CreatePod(ctx, req.(*CreatePodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_UpdatePod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).UpdatePod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K8SService_UpdatePod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).UpdatePod(ctx, req.(*UpdatePodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_DeletePod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).DeletePod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K8SService_DeletePod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).DeletePod(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_CreateDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).CreateDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K8SService_CreateDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).CreateDeployment(ctx, req.(*CreateDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_UpdateDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).UpdateDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K8SService_UpdateDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).UpdateDeployment(ctx, req.(*UpdateDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_DeleteDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).DeleteDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K8SService_DeleteDeployment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).DeleteDeployment(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K8SService_CreateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).CreateService(ctx, req.(*CreateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_UpdateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).UpdateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K8SService_UpdateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).UpdateService(ctx, req.(*UpdateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_DeleteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).DeleteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K8SService_DeleteService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).DeleteService(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_CreateConfigMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConfigMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).CreateConfigMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K8SService_CreateConfigMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).CreateConfigMap(ctx, req.(*CreateConfigMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_UpdateConfigMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).UpdateConfigMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K8SService_UpdateConfigMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).UpdateConfigMap(ctx, req.(*UpdateConfigMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_DeleteConfigMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).DeleteConfigMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K8SService_DeleteConfigMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).DeleteConfigMap(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_ListNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).ListNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K8SService_ListNamespaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).ListNamespaces(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_GetPodLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SServiceServer).GetPodLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K8SService_GetPodLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SServiceServer).GetPodLogs(ctx, req.(*PodLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SService_ExecPod_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(K8SServiceServer).ExecPod(m, &grpc.GenericServerStream[ExecRequest, ExecResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type K8SService_ExecPodServer = grpc.ServerStreamingServer[ExecResponse]

// K8SService_ServiceDesc is the grpc.ServiceDesc for K8SService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var K8SService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "k8s.K8sService",
	HandlerType: (*K8SServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPods",
			Handler:    _K8SService_ListPods_Handler,
		},
		{
			MethodName: "ListDeployments",
			Handler:    _K8SService_ListDeployments_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _K8SService_ListServices_Handler,
		},
		{
			MethodName: "ListConfigMaps",
			Handler:    _K8SService_ListConfigMaps_Handler,
		},
		{
			MethodName: "CreatePod",
			Handler:    _K8SService_CreatePod_Handler,
		},
		{
			MethodName: "UpdatePod",
			Handler:    _K8SService_UpdatePod_Handler,
		},
		{
			MethodName: "DeletePod",
			Handler:    _K8SService_DeletePod_Handler,
		},
		{
			MethodName: "CreateDeployment",
			Handler:    _K8SService_CreateDeployment_Handler,
		},
		{
			MethodName: "UpdateDeployment",
			Handler:    _K8SService_UpdateDeployment_Handler,
		},
		{
			MethodName: "DeleteDeployment",
			Handler:    _K8SService_DeleteDeployment_Handler,
		},
		{
			MethodName: "CreateService",
			Handler:    _K8SService_CreateService_Handler,
		},
		{
			MethodName: "UpdateService",
			Handler:    _K8SService_UpdateService_Handler,
		},
		{
			MethodName: "DeleteService",
			Handler:    _K8SService_DeleteService_Handler,
		},
		{
			MethodName: "CreateConfigMap",
			Handler:    _K8SService_CreateConfigMap_Handler,
		},
		{
			MethodName: "UpdateConfigMap",
			Handler:    _K8SService_UpdateConfigMap_Handler,
		},
		{
			MethodName: "DeleteConfigMap",
			Handler:    _K8SService_DeleteConfigMap_Handler,
		},
		{
			MethodName: "ListNamespaces",
			Handler:    _K8SService_ListNamespaces_Handler,
		},
		{
			MethodName: "GetPodLogs",
			Handler:    _K8SService_GetPodLogs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecPod",
			Handler:       _K8SService_ExecPod_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/k8s.proto",
}
